version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_PASSWORD=7PSPdHVz7eSb3mHumLVq
      - xpack.security.enabled=true
      - path.repo=/usr/share/elasticsearch/data/backup
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      # - ./certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    environment:
      # - elasticsearch.username="kibana_system"
      # - elasticsearch.password="111111"
      - elasticsearch.hosts=["elasticsearch:9200"]
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: logstash:8.12.2
    labels:
      co.elastic.logs/module: logstash
    user: root
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    #   - NODE_NAME="logstash"
    #   - xpack.monitoring.enabled=false
      
    #   - ELASTIC_HOSTS=https://elasticsearch:9200
    # command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  filebeat:
    image: elastic/filebeat:8.12.2
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
    networks:
      - elastic
volumes:
  elasticsearch-data:  # Optional volume for Elasticsearch data persistence

networks:
  elastic:
    driver: bridge