version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - ELASTIC_PASSWORD=111111
      - xpack.security.enabled=false
      # - xpack.security.enrollment.enabled=true
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      # - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    environment:
        # - elasticsearch.username="elastic"
        # - elasticsearch.password="111111"
        # - elasticsearch.hosts=["elasticsearch:9200"]
        # - elasticsearch_ssl_verificationMode="certificate"
        # - elasticsearch_url="host.docker.internal:9200"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN=generated_token_here
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.3
    labels:
      co.elastic.logs/module: logstash
    user: root
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    #   - NODE_NAME="logstash"
    #   - xpack.monitoring.enabled=false
      
    #   - ELASTIC_HOSTS=https://elasticsearch:9200
    # command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  elasticsearch-data:
  # logstashdata:

networks:
  elastic:
    driver: bridge